import { RawProductData } from '../service/ProductService';

export const MOCK_PRODUCTS: RawProductData[] = [
  {
    imageKey: 'ic_holder_50e',
    name: 'XXX50E',
    discount: '',
    price: '¥4088',
    promotion: '',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_xs2',
    name: 'XXXPadMate Xs 2 \n8GB+256GB （雅黑）',
    discount: '',
    price: '¥9999',
    promotion: '限时',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_computer',
    name: 'XX设备  新品优惠！新品优惠！机不可失！失不再来！快来购买！快来购买！',
    discount: '限时省200',
    price: '¥10099',
    promotion: '商品',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_mouse',
    name: '送给亲人  快速购买！',
    discount: '限时省200',
    price: '¥199',
    promotion: '',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_pad',
    name: 'XXXPad Pro',
    discount: '',
    price: '¥3499',
    promotion: '',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_mate50',
    name: 'XXXMate 50 8GB+256GB',
    discount: '',
    price: '¥5499',
    promotion: '',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_60pro',
    name: 'XXX60 Pro 新品上市！\n你值得拥有！\n限时折扣！\n速速购买！',
    discount: '限时省200',
    price: '¥1299',
    promotion: '限时',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_50e',
    name: 'XXX50E',
    discount: '',
    price: '¥4088',
    promotion: '',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_xs2',
    name: 'XXXPadMate Xs 2 \n8GB+256GB （雅黑）',
    discount: '限时省200',
    price: '¥9999',
    promotion: '限时',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_computer',
    name: 'XX设备  新品优惠！新品优惠！',
    discount: '限时省200',
    price: '¥10099',
    promotion: '商品',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_mouse',
    name: '送给亲人  快速购买！',
    discount: '限时省200',
    price: '¥199',
    promotion: '限时',
    bonus_points: '赠送积分'
  },
  {
    imageKey: 'ic_holder_pad',
    name: 'XXXPad Pro\n限时折扣！\n速速购买！\n机不可失！失不再来！',
    discount: '限时省200',
    price: '¥3499',
    promotion: '',
    bonus_points: '赠送积分'
  },
  {
    imageKey: 'ic_holder_mate50',
    name: 'XXXMate 50 \n8GB+256GB',
    discount: '',
    price: '¥5499',
    promotion: '',
    bonus_points: ''
  },
  {
    imageKey: 'ic_holder_60pro',
    name: 'XXX60 Pro',
    discount: '限时省200',
    price: '¥1299',
    promotion: '限时',
    bonus_points: '',
  }
];